language: node_js
node_js:
  - 12
before_deploy:
  - 'git config --global user.email "opensource@groupon.com"'
  - 'git config --global user.name "Groupon"'
deploy:
  provider: script
  script: npx nlm release
  skip_cleanup: true
  'on':
    branch: master
    node: 12
